kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: eaglejenk-pvc
  namespace: eaglejenk
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 2Gi
